# Generated by Django 4.2.23 on 2026-02-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_address_student_course_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
    ]
