# Generated by Django 4.2.23 on 2026-03-09 05:55

from django.db import migrations

def create_initial_note(apps, schema_editor ):
    Note = apps.get_model('notes', 'Note')
    Note.objects.create(
        title='note 1',
        content = 'this is manual data added with manual migration file ' 
    )

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_note),
    ]
