# Generated by Django 4.2.23 on 2026-03-09 06:22

from django.db import migrations

def update_initial_note(apps, schema_editor ):
    Note = apps.get_model('notes', 'Note')
    Note.objects.bulk_create([
        Note(title = "note 2" , content = "created mynotes project"),
        Note(title = "note 3" , content = "created notes app"),
        Note(title = "note 4" , content = "created database mynotes"),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20260309_1125'),
    ]

    operations = [
        migrations.RunPython(update_initial_note)
    ]
