# Generated by Django 4.2.23 on 2026-03-09 12:05

from django.db import migrations

def add_initial_note(apps, schema_editor ):
    Note = apps.get_model('notes', 'Note')
    Note.objects.bulk_create([
        Note(title = "note 5" , content = "learn manual migration"),
        Note(title = "note 6" , content = "created migration files"),
        Note(title = "note 7" , content = "created data migration file for data insert "),
    ])
class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20260309_1152'),
    ]

    operations = [
        migrations.RunPython(add_initial_note)
    ]
